import "@/app/globals.css";
import { balsamiqSans } from "./fonts";
import Provider from "@/lib/session-context";
import { getServerSession } from "next-auth";
import { options } from "@/lib/auth";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(options);

  return (
    <html lang="en">
      <Provider session={session}>
        <body className={`${balsamiqSans.className}`}>{children}</body>
      </Provider>
    </html>
  );
}
