import "@/app/globals.css";
import { balsamiqSans } from "./fonts";

export const metadata = {
	title: "Next.js",
	description: "Generated by Next.js",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={`${balsamiqSans.className} px-12`}>
				{/* <Header /> */}
				{children}
			</body>
		</html>
	);
}
